/**
 * Messages repository.
 *
 * One row per chat turn. `id` is the SSE messageId that the widget already
 * receives in the `meta` event — so feedback (Drop 3) can reference messages
 * by the same id the client knows about.
 *
 * `content` is ALREADY PII-redacted before it gets here (see piiRedaction.js).
 */

const { query } = require('../index');

/**
 * Insert a message.
 *
 * @param {object} params
 * @param {string} params.id                - UUID (must be pre-generated by caller)
 * @param {string} params.conversationId    - internal UUID of conversation
 * @param {string} params.role              - 'user' | 'assistant'
 * @param {string} params.content           - already-redacted text
 * @param {string|null} params.language
 * @param {string|null} params.path         - 'fast' | 'complex' | 'order'
 * @param {string|null} params.model
 * @param {Array<string>|null} params.toolCalls
 * @param {boolean|null} params.embeddingCached
 * @param {number|null} params.latencyMs
 * @param {number|null} params.tokenCount
 * @returns {Promise<{id: string} | null>}
 */
async function insert(params) {
  const {
    id,
    conversationId,
    role,
    content,
    language = null,
    path = null,
    model = null,
    toolCalls = null,
    embeddingCached = null,
    latencyMs = null,
    tokenCount = null,
  } = params;

  if (!id || !conversationId || !role || !content) return null;

  const result = await query(
    `INSERT INTO messages
       (id, conversation_id, role, content, language, path, model,
        tool_calls, embedding_cached, latency_ms, token_count)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
     ON CONFLICT (id) DO NOTHING
     RETURNING id`,
    [
      id,
      conversationId,
      role,
      content,
      language,
      path,
      model,
      toolCalls ? JSON.stringify(toolCalls) : null,
      embeddingCached,
      latencyMs,
      tokenCount,
    ]
  );

  return result?.rows?.[0] || null;
}

/**
 * Get a message by its id.
 */
async function findById(id) {
  const result = await query('SELECT * FROM messages WHERE id = $1', [id]);
  return result?.rows?.[0] || null;
}

/**
 * Get all messages in a conversation (ordered chronologically).
 */
async function findByConversationId(conversationId) {
  const result = await query(
    'SELECT * FROM messages WHERE conversation_id = $1 ORDER BY created_at ASC',
    [conversationId]
  );
  return result?.rows || [];
}

/**
 * Find slow assistant messages (latency_ms > threshold).
 * Useful for ops dashboards.
 */
async function findSlow(thresholdMs = 5000, limit = 50) {
  const result = await query(
    `SELECT m.id, m.content, m.path, m.latency_ms, m.created_at, c.conversation_id
       FROM messages m JOIN conversations c ON m.conversation_id = c.id
      WHERE m.role = 'assistant' AND m.latency_ms > $1
      ORDER BY m.created_at DESC
      LIMIT $2`,
    [thresholdMs, limit]
  );
  return result?.rows || [];
}

/**
 * Aggregate path distribution + latency stats for a time window.
 */
async function getPathStats(intervalText = '7 days') {
  const result = await query(
    `SELECT path, COUNT(*) as count,
            ROUND(AVG(latency_ms))::int as avg_ms,
            ROUND(PERCENTILE_CONT(0.5)  WITHIN GROUP (ORDER BY latency_ms))::int as p50_ms,
            ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY latency_ms))::int as p95_ms
       FROM messages
      WHERE role = 'assistant'
        AND created_at > NOW() - INTERVAL '${intervalText.replace(/'/g, '')}'
      GROUP BY path
      ORDER BY count DESC`
  );
  return result?.rows || [];
}

module.exports = {
  insert,
  findById,
  findByConversationId,
  findSlow,
  getPathStats,
};
